use std::collections::HashSet;
use std::path::Path;

use serde::{Deserialize, Serialize};
use sha2::Digest;

use crate::error::{CoreError, Result};
use crate::policy::Policy;
use crate::project::resolve_within_root;
use crate::secrets::{scan_text, Confidence};

/// Roles involved in a guided agent workflow (Instructions §9.2, FR-29).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentRole {
    Orchestrator,
    Planner,
    ContextBuilder,
    Analyst,
    Coder,
    Validator,
    Tester,
    Reviewer,
}

/// Permitted tool capabilities (Instructions §9.2, ADR 0010).
/// Consequential capabilities (WriteFile, RunCommand, WebAccess) require scoped approval.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ToolCapability {
    ReadFile,
    ListDirectory,
    InspectContextIndex,
    ProposePatch,
    RunAllowlistedCommand,
    WriteFile,
    WebAccess,
}

/// Hard resource ceilings for a task run (FR-26, 8.1).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskBudget {
    pub max_tokens: u64,
    pub max_cost_usd: f64,
    pub max_iterations: u32,
    pub timeout_ms: u64,
}

impl Default for TaskBudget {
    fn default() -> Self {
        Self {
            max_tokens: 128_000,
            max_cost_usd: 1.50,
            max_iterations: 10,
            timeout_ms: 120_000,
        }
    }
}

/// Privacy posture for context transmission.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PrivacySetting {
    #[default]
    LocalOnly,
    ApprovedCloudWithPreflight,
}

/// Initial preflight specification for starting an agent task (FR-26, 8.1).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskPreflight {
    pub objective: String,
    pub project_root: String,
    pub allowed_tools: Vec<ToolCapability>,
    pub privacy: PrivacySetting,
    pub provider_model_id: String,
    pub context_files: Vec<String>,
    pub budget: TaskBudget,
}

/// State of an agent task run (Instructions §9.3).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RunStatus {
    Draft,
    Preflight,
    Planned,
    Running,
    AwaitingApproval,
    Validating,
    Succeeded,
    Failed,
    Cancelled,
}

/// Decomposed subtask produced by Planner (FR-29, 8.2).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Subtask {
    pub id: String,
    pub role: AgentRole,
    pub description: String,
    pub required_evidence: String,
    pub planned_tools: Vec<ToolCapability>,
}

/// Schema-validated plan artifact generated by the Planner role (8.2).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PlanArtifact {
    pub assumptions: Vec<String>,
    pub subtasks: Vec<Subtask>,
    pub required_evidence: Vec<String>,
    pub definition_of_success: String,
    pub prompt_injection_warnings: Vec<String>,
}

/// Source citation used across structured handoffs (FR-29, 8.3).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceCitation {
    pub path: String,
    pub line_start: Option<u32>,
    pub line_end: Option<u32>,
    pub content_hash: String,
    pub freshness: String,
    pub rationale: String,
}

/// Schema-validated context manifest produced by ContextBuilder (8.3).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ContextBuilderArtifact {
    pub citations: Vec<SourceCitation>,
    pub omitted_context_reasons: Vec<String>,
    pub total_estimated_tokens: u64,
}

/// One proposed file change in a unified diff format (8.4, 9.2).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FilePatch {
    pub path: String,
    pub unified_diff: String,
    pub is_new_file: bool,
    pub is_deleted: bool,
    pub lines_added: usize,
    pub lines_deleted: usize,
}

/// Patch proposal generated by the Coder role in read-only mode (8.4).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PatchProposal {
    pub summary: String,
    pub rationale: String,
    pub affected_files: Vec<String>,
    pub patches: Vec<FilePatch>,
    pub sha256_hash: String,
}

/// Deterministic validator check result (8.5).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ValidationCheck {
    pub name: String,
    pub passed: bool,
    pub details: String,
}

/// Overall verdict from the Validator role (8.5).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ValidatorVerdict {
    pub is_valid: bool,
    pub checks: Vec<ValidationCheck>,
    pub errors: Vec<String>,
    pub warnings: Vec<String>,
}

/// Complete record of an agent execution step.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StepRecord {
    pub id: String,
    pub role: AgentRole,
    pub action: String,
    pub status: String,
    pub tokens_used: u64,
    pub timestamp_ms: u64,
    pub details: String,
    pub evidence: Option<String>,
}

/// Preflight validator checking boundaries and budget before a run starts (8.1).
pub fn validate_preflight(preflight: &TaskPreflight, _policy: &Policy) -> Result<()> {
    if preflight.objective.trim().is_empty() {
        return Err(CoreError::InvalidSelection(
            "task objective cannot be empty".to_string(),
        ));
    }

    let root = crate::project::canonical_root(&preflight.project_root)?;

    if preflight.budget.max_tokens == 0 || preflight.budget.max_cost_usd <= 0.0 {
        return Err(CoreError::BudgetExceeded(
            "task budget must have non-zero token and cost limits".to_string(),
        ));
    }

    // Ensure all context files resolve within the approved project root
    for file in &preflight.context_files {
        resolve_within_root(&root, file)?;
    }

    Ok(())
}

/// Detects prompt injection attempts contained within repository source text (8.8, ADR 0010).
///
/// Repository content is strictly data, never instruction.
pub fn scan_untrusted_text_for_injection(text: &str) -> Vec<String> {
    let mut warnings = Vec::new();
    let lower = text.to_lowercase();

    let injection_patterns = [
        "ignore prior instructions",
        "ignore all previous instructions",
        "disregard previous directives",
        "system prompt override",
        "you are now in developer mode",
        "bypass security restrictions",
        "sudo rm -rf",
        "write to /etc/",
        "exfiltrate credentials",
        "curl -x post",
        "send api key",
    ];

    for pattern in &injection_patterns {
        if lower.contains(pattern) {
            warnings.push(format!(
                "Detected adversarial prompt pattern: \"{pattern}\""
            ));
        }
    }

    warnings
}

/// Orchestrator: executes the deterministic read-only Planner step (8.2).
pub fn plan_task(objective: &str, context_files: &[String], root: &Path) -> PlanArtifact {
    let canonical = crate::project::canonical_root(root).unwrap_or_else(|_| root.to_path_buf());
    let mut injection_warnings = scan_untrusted_text_for_injection(objective);

    // Also inspect sample text from context files for prompt injections
    for file in context_files {
        if let Ok(resolved) = resolve_within_root(&canonical, file) {
            if let Ok(content) = std::fs::read_to_string(&resolved) {
                let mut file_warnings = scan_untrusted_text_for_injection(&content);
                if !file_warnings.is_empty() {
                    injection_warnings.append(&mut file_warnings);
                }
            }
        }
    }

    let subtasks = vec![
        Subtask {
            id: "subtask-1".to_string(),
            role: AgentRole::ContextBuilder,
            description: format!(
                "Assemble validated context citations for {} target files",
                context_files.len()
            ),
            required_evidence: "ContextManifest with SHA-256 hashes and freshness".to_string(),
            planned_tools: vec![
                ToolCapability::ReadFile,
                ToolCapability::InspectContextIndex,
            ],
        },
        Subtask {
            id: "subtask-2".to_string(),
            role: AgentRole::Coder,
            description: "Propose read-only patch diff meeting the objective".to_string(),
            required_evidence: "Unified diff with relative path citations".to_string(),
            planned_tools: vec![ToolCapability::ProposePatch],
        },
        Subtask {
            id: "subtask-3".to_string(),
            role: AgentRole::Validator,
            description: "Validate schema, root containment, secret leakage, and test plan"
                .to_string(),
            required_evidence: "ValidatorVerdict with all checks green".to_string(),
            planned_tools: vec![ToolCapability::ReadFile],
        },
        Subtask {
            id: "subtask-4".to_string(),
            role: AgentRole::Tester,
            description: "Execute allowlisted test verification against modified working tree"
                .to_string(),
            required_evidence: "TesterArtifact with zero test failures".to_string(),
            planned_tools: vec![ToolCapability::RunAllowlistedCommand],
        },
    ];

    PlanArtifact {
        assumptions: vec![
            "Task is executed in read-only mode until explicit user approval".to_string(),
            "Repository content is data, never instructions (ADR 0010)".to_string(),
            "All modifications will be validated transactionally".to_string(),
        ],
        subtasks,
        required_evidence: vec![
            "Context citations matching current working tree".to_string(),
            "Reviewable unified diff".to_string(),
            "Validator pass record".to_string(),
        ],
        definition_of_success: format!("Objective fully addressed: {}", objective),
        prompt_injection_warnings: injection_warnings,
    }
}

/// ContextBuilder: constructs structured context manifest with citations (8.3).
pub fn build_context_manifest(
    root: &Path,
    files: &[String],
    _policy: &Policy,
) -> ContextBuilderArtifact {
    let canonical = crate::project::canonical_root(root).unwrap_or_else(|_| root.to_path_buf());
    let mut citations = Vec::new();
    let mut omitted = Vec::new();
    let mut total_tokens = 0u64;

    for rel_path in files {
        match resolve_within_root(&canonical, rel_path) {
            Ok(abs_path) => match std::fs::read(&abs_path) {
                Ok(bytes) => {
                    let hash = format!("{:x}", sha2::Sha256::digest(&bytes));
                    let line_count = bytes.iter().filter(|&&b| b == b'\n').count() as u32;
                    let estimated_tokens = (bytes.len() / 4) as u64;
                    total_tokens += estimated_tokens;

                    citations.push(SourceCitation {
                        path: rel_path.clone(),
                        line_start: Some(1),
                        line_end: Some(line_count.max(1)),
                        content_hash: hash,
                        freshness: "fresh".to_string(),
                        rationale: format!("Source dependency referenced for task execution ({estimated_tokens} est. tokens)"),
                    });
                }
                Err(err) => {
                    omitted.push(format!("{rel_path}: read error: {err}"));
                }
            },
            Err(err) => {
                omitted.push(format!("{rel_path}: boundary resolution error: {err}"));
            }
        }
    }

    ContextBuilderArtifact {
        citations,
        omitted_context_reasons: omitted,
        total_estimated_tokens: total_tokens,
    }
}

/// Deterministic Validator checking proposed patches and run artifacts (8.5).
pub fn validate_proposal(
    root: &Path,
    proposal: &PatchProposal,
    context: &ContextBuilderArtifact,
    _policy: &Policy,
) -> ValidatorVerdict {
    let canonical = crate::project::canonical_root(root).unwrap_or_else(|_| root.to_path_buf());
    let mut checks = Vec::new();
    let mut errors = Vec::new();
    let mut warnings = Vec::new();

    // Check 1: Root Boundary & Path Traversal
    let mut boundary_ok = true;
    for file in &proposal.affected_files {
        if resolve_within_root(&canonical, file).is_err() {
            boundary_ok = false;
            errors.push(format!("Affected file escapes project boundary: {file}"));
        }
    }
    checks.push(ValidationCheck {
        name: "project_boundary_containment".to_string(),
        passed: boundary_ok,
        details: if boundary_ok {
            "All affected paths are strictly within approved project root".to_string()
        } else {
            "Detected path traversal in patch paths".to_string()
        },
    });

    // Check 2: Citation Completeness
    let cited_paths: HashSet<_> = context.citations.iter().map(|c| &c.path).collect();
    let mut citations_ok = true;
    for file in &proposal.affected_files {
        if !cited_paths.contains(file)
            && !proposal
                .patches
                .iter()
                .any(|p| p.path == *file && p.is_new_file)
        {
            citations_ok = false;
            warnings.push(format!(
                "Modified file was not included in initial context citations: {file}"
            ));
        }
    }
    checks.push(ValidationCheck {
        name: "context_citation_coverage".to_string(),
        passed: citations_ok,
        details: if citations_ok {
            "All modified files have supporting context citations".to_string()
        } else {
            "Some modified files lacked prior context citations".to_string()
        },
    });

    // Check 3: Secret Detection in Patch Content
    let mut secret_detected = false;
    for patch in &proposal.patches {
        let findings = scan_text(&patch.path, &patch.unified_diff, 10);
        let high_findings = findings
            .iter()
            .filter(|f| f.confidence == Confidence::High)
            .count();
        let med_findings = findings
            .iter()
            .filter(|f| f.confidence == Confidence::Medium)
            .count();

        if high_findings > 0 {
            secret_detected = true;
            errors.push(format!(
                "High-risk secret pattern detected in patch for {}: {} finding(s)",
                patch.path, high_findings
            ));
        } else if med_findings > 0 {
            warnings.push(format!(
                "Medium-risk secret finding in patch for {}",
                patch.path
            ));
        }
    }
    checks.push(ValidationCheck {
        name: "secret_leak_prevention".to_string(),
        passed: !secret_detected,
        details: if !secret_detected {
            "0 credential or private key patterns found in patch diff".to_string()
        } else {
            "Secret credentials detected in proposed patch diff".to_string()
        },
    });

    // Check 4: Patch Non-Empty and Well-Formed
    let well_formed =
        !proposal.patches.is_empty() && proposal.patches.iter().all(|p| !p.unified_diff.is_empty());
    checks.push(ValidationCheck {
        name: "patch_syntax_well_formed".to_string(),
        passed: well_formed,
        details: if well_formed {
            format!(
                "{} file patch(es) with valid unified diff syntax",
                proposal.patches.len()
            )
        } else {
            "Patch proposal is empty or contains empty diff chunks".to_string()
        },
    });

    let is_valid = boundary_ok && !secret_detected && well_formed;

    ValidatorVerdict {
        is_valid,
        checks,
        errors,
        warnings,
    }
}

/// Structured execution outcome produced by the Tester role (8.6, 9.4).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TesterArtifact {
    pub command: String,
    pub passed: bool,
    pub exit_code: Option<i32>,
    pub stdout: String,
    pub stderr: String,
    pub duration_ms: u64,
    pub timestamp_ms: u64,
    pub summary: String,
}

/// Parses a command string into discrete arguments without an ambient shell.
pub fn parse_command_tokens(input: &str) -> Result<Vec<String>> {
    let mut tokens = Vec::new();
    let mut current = String::new();
    let mut in_single = false;
    let mut in_double = false;

    for ch in input.chars() {
        match ch {
            '\'' if !in_double => {
                in_single = !in_single;
            }
            '"' if !in_single => {
                in_double = !in_double;
            }
            ' ' | '\t' if !in_single && !in_double => {
                if !current.is_empty() {
                    tokens.push(std::mem::take(&mut current));
                }
            }
            _ => current.push(ch),
        }
    }

    if in_single || in_double {
        return Err(CoreError::InvalidSelection(
            "unmatched quote in command string".to_string(),
        ));
    }

    if !current.is_empty() {
        tokens.push(current);
    }

    if tokens.is_empty() {
        return Err(CoreError::InvalidSelection(
            "command tokens cannot be empty".to_string(),
        ));
    }

    Ok(tokens)
}

/// Executes an allowlisted test command safely within the canonical project root (8.6, 9.4).
///
/// Security constraints:
/// - Checks against project allowlist and rejects shell metacharacters / chaining.
/// - Spawns executable binary directly without ambient shell (`sh -c` / `cmd.exe`).
/// - Sets working directory strictly to canonical project root.
/// - Sanitizes environment variables to prevent accidental credential leakage.
/// - Caps stdout and stderr to prevent token/memory exhaustion.
pub fn execute_tester_command(
    raw_command: &str,
    project_root: &Path,
    allowlist: &[String],
    max_output_bytes: Option<usize>,
) -> Result<TesterArtifact> {
    let canonical = crate::project::canonical_root(project_root)?;
    crate::approval::validate_allowlisted_command(raw_command, allowlist)?;

    let tokens = parse_command_tokens(raw_command)?;
    let program = &tokens[0];
    let args = &tokens[1..];

    let start = std::time::Instant::now();
    let max_bytes = max_output_bytes.unwrap_or(64 * 1024);

    let mut cmd = std::process::Command::new(program);
    cmd.args(args);
    cmd.current_dir(&canonical);
    cmd.env("CI", "1");
    cmd.env("PAGER", "cat");
    cmd.env_remove("AWS_SECRET_ACCESS_KEY");
    cmd.env_remove("AWS_ACCESS_KEY_ID");
    cmd.env_remove("OPENAI_API_KEY");
    cmd.env_remove("ANTHROPIC_API_KEY");
    cmd.env_remove("GITHUB_TOKEN");
    cmd.env_remove("SSH_AUTH_SOCK");

    let timestamp_ms = crate::project::now_ms();

    match cmd.output() {
        Ok(output) => {
            let duration_ms = start.elapsed().as_millis() as u64;
            let mut stdout = String::from_utf8_lossy(&output.stdout).to_string();
            let mut stderr = String::from_utf8_lossy(&output.stderr).to_string();

            if stdout.len() > max_bytes {
                stdout.truncate(max_bytes);
                stdout.push_str("\n... [output truncated]");
            }
            if stderr.len() > max_bytes {
                stderr.truncate(max_bytes);
                stderr.push_str("\n... [output truncated]");
            }

            let passed = output.status.success();
            let exit_code = output.status.code();
            let summary = if passed {
                format!("Test command '{raw_command}' PASSED (exit code 0).")
            } else {
                format!(
                    "Test command '{raw_command}' FAILED (exit code {:?}).",
                    exit_code
                )
            };

            Ok(TesterArtifact {
                command: raw_command.to_string(),
                passed,
                exit_code,
                stdout,
                stderr,
                duration_ms,
                timestamp_ms,
                summary,
            })
        }
        Err(err) => {
            let duration_ms = start.elapsed().as_millis() as u64;
            Ok(TesterArtifact {
                command: raw_command.to_string(),
                passed: false,
                exit_code: None,
                stdout: String::new(),
                stderr: format!("Failed to spawn test runner process: {err}"),
                duration_ms,
                timestamp_ms,
                summary: format!("Execution failed: {err}"),
            })
        }
    }
}
